/**
 * Set an array of english abusive words
 * 
 * @todo check the list and add more bad words
 */
const en: string[] = [
  "^2g1c$",
  "^4r5e$",
  "^50 yard cunt punt$",
  "^5h1t$|^5hit$|^5ht$",
  "^666$",
  "^a2m$",
  "^a54$",
  "^abbo$",
  "^abeed$",
  "^abuse$",
  "^acrotomophilia$",
  "^addicts$",
  "^aeolus$",
  "^africoon$",
  "^alabama hot pocket$",
  "^alaskan pipeline$",
  "^alligator bait$|^alligatorbait$",
  "^amateur$",
  "^amcik$",
  "^anal$|^anal impaler$|^anal leakage$|^analannie$|^analprobe$|^analsex$",
  "^andskota$",
  "^anilingus$",
  "^anus$",
  "^apeshit$",
  "^ar5e$",
  "^arabush$|^arabushs$",
  "^areola$|^areole$",
  "^argie$",
  "^arian$",
  "^armo$|^armos$",
  "^aroused$",
  "^arrse$|^arse$|^arsehole$|^arses$",
  "^arschloch$",
  "^aryan$",
  "^ass fuck$",
  "^ass hole$",
  "^ass monkey$",
  "^ass-fucker$",
  "^ass-hat$",
  "^ass-jabber$",
  "^ass-pirate$",
  "^assbag$|^assbagger$",
  "^assbandit$",
  "^assbang$|^assbanged$|^assbanger$|^assbangs$",
  "^assbite$",
  "^assblaster$",
  "^assclown$",
  "^asscock$",
  "^asscowboy$",
  "^asscracker$",
  "^asses$",
  "^assface$|^assfaces$",
  "^assfuck$|^assfucker$|^assfukka$",
  "^assgoblin$",
  "^asshat$",
  "^asshead$",
  "^asshole$|^ahole$|^assho1e$|^a55hole$|^assholes$|^assholz$|^a s shole$",
  "^ash0le$|^ash0les$|^asholes$|^assh0le$|^assh0lez$",
  "^asholes$",
  "^asshopper$",
  "^asshore$",
  "^assjacker$|^assjockey$",
  "^asskiss$|^asskisser$",
  "^assklown$",
  "^asslick$|^asslicker$",
  "^asslover$",
  "^assman$",
  "^assmaster$",
  "^assmonkey$",
  "^assmucus$",
  "^assmunch$",
  "^assmuncher$",
  "^assnigger$",
  "^asspacker$",
  "^asspirate$",
  "^asspuppies$",
  "^assrammer$",
  "^assranger$",
  "^assshit$",
  "^assshole$",
  "^asssucker$",
  "^asswad$",
  "^asswhole$",
  "^asswhore$",
  "^asswipe$",
  "^asswipes$",
  "^auto erotic$",
  "^autoerotic$",
  "^axwound$",
  "^ayir$",
  "^azazel$",
  "^azz$|^azzhole$",
  "^babe$|^babes$|^babeland$",
  "^baby batter$|^baby juice$",
  "^backdoor$|^backdoorman$",
  "^badfuck$",
  "^bagging$",
  "^ball gag$",
  "^ball gravy$",
  "^ball kicking$",
  "^ball licking$",
  "^ball sack$",
  "^ball sucking$",
  "^ballbag$",
  "^balllicker$",
  "^balls$",
  "^ballsack$",
  "^bampot$",
  "^bang$|^bang one box$|^bang box$",
  "^bangbro$|^bangbros$",
  "^banger$",
  "^banging$",
  "^bareback$",
  "^barelylegal$|^barely legal$",
  "^barenaked$",
  "^barf$",
  "^barface$|^barfface$",
  "^bassterd$|^bassterds$",
  "^bastard$|^b a s t a r d$",
  "^bastardo$|^bastards$|^bastardz$|^basterds$|^basterdz$",
  "^bastinado$",
  "^batty boy$",
  "^bawdy$",
  "^bazongas$",
  "^bazooms$",
  "^bbw$",
  "^bdsm$",
  "^beaner$|^beaners$",
  "^beaney$|^beaneys$",
  "^beardedclam$",
  "^beastality$|^beastial$|^beastiality$|^beastility$",
  "^beatch$",
  "^beater$",
  "^beatoff$",
  "^beatyourmeat$",
  "^beaver$|^beaver cleaver$|^beaver lips$",
  "^beef curtain$|^beef curtains$",
  "^beeyotch$",
  "^bellend$",
  "^bender$",
  "^beotch$",
  "^bescumber$",
  "^bestial$|^bestiality$",
  "^bicurious$|^bi curious$",
  "^big black$",
  "^big breasts$",
  "^big knockers$",
  "^big tits$",
  "^bigass$",
  "^bigbastard$",
  "^bigbreasts$",
  "^bigbutt$",
  "^bigtits$",
  "^bimbo$|^bimbos$",
  "^bint$",
  "^birdlock$",
  "^b17ch$|^bi7ch$|^b1tch$|^b7ch$",
  "^bitch$|^biatch$|^btch$",
  "^bitch tit$",
  "^bitchass$",
  "^bitchboy$",
  "^bitched$",
  "^bitcher$",
  "^bitchers$",
  "^bitches$",
  "^bitchez$",
  "^bitchin$",
  "^bitching$",
  "^bitchslap$",
  "^bitchtit$",
  "^bitchtits$",
  "^bitchy$",
  "^biteme$",
  "^black cock$",
  "^blackcock$",
  "^blackman$",
  "^blackout$",
  "^blacks$",
  "^blew his load$",
  "^blonde action$|^blonde on blonde$|^blonde on blonde action$",
  "^bloodclaat$",
  "^bloody hell$",
  "^blow$",
  "^blow his load$",
  "^blow j$",
  "^blow job$",
  "^blow me$",
  "^blow mud$",
  "^blow your l$",
  "^blow your load$",
  "^blowjob$|^blowjobs$",
  "^blue waffle$",
  "^bluegum$|^bluegums$",
  "^blumpkin$",
  "^boang$",
  "^boche$|^boches$",
  "^bodily$",
  "^boffing$",
  "^bogan$",
  "^bohunk$",
  "^boink$",
  "^boiolas$",
  "^bollick$",
  "^bollock$|^bollocks$",
  "^bollok$|^bollox$",
  "^bombers$",
  "^bombing$",
  "^bomd$",
  "^bondage$",
  "^boned$",
  "^boner$|^boners$",
  "^bong$",
  "^boob$|^boobies$",
  "^boobs$|^b o o b$|^bo ob$|^bo obs$",
  "^b00b$|^b00b5$|^b00bies$|^b00biez$|^b00bs$|^b00bz$",
  "^booobs$|^boooobs$|^booooobs$|^booooooobs$",
  "^booby$",
  "^boobz$",
  "^boody$",
  "^booger$",
  "^bookie$",
  "^boong$",
  "^boonga$|^boongas$",
  "^boongs$",
  "^boonie$|^boonies$",
  "^bootee$|^bootie$",
  "^bootlip$|^bootlips$",
  "^booty$|^booty call$|^bootycall$",
  "^booze$|^boozer$|^boozy$",
  "^bosch$",
  "^bosom$|^bosomy$",
  "^bountybar$|^bounty bar$|^bounty bars$",
  "^bowel$|^bowels$",
  "^bra$",
  "^brassiere$",
  "^brea5t$",
  "^breeder$",
  "^breast$|^breasts$",
  "^breastjob$",
  "^breastlover$",
  "^breastman$",
  "^brothel$",
  "^brotherfucker$",
  "^brown showers$",
  "^brunette action$",
  "^buceta$",
  "^buddhahead$|^buddhaheads$",
  "^buffies$",
  "^bugger$|^buggered$|^buggery$",
  "^bukkake$",
  "^bule$|^bules$",
  "^bull shit$",
  "^bullcrap$",
  "^bulldike$|^bulldyke$",
  "^bullet vibe$",
  "^bullshit$",
  "^bullturds$",
  "^bum$|^bum boy$",
  "^bumblefuck$",
  "^bumclat$",
  "^bumfuck$",
  "^buncombe$",
  "^bung$|^bung hole$",
  "^bunga$|^bungas$|^bunghole$",
  "^bunny fucker$",
  "^burr head$|^burr heads$",
  "^burrhead$|^burrheads$",
  "^bust a load$",
  "^busty$",
  "^butchbabes$",
  "^butchdike$|^butchdyke$",
  "^butt$|^butt fuck$|^butt plug$|^butt-pirate$",
  "^buttbang$",
  "^buttcheeks$",
  "^buttface$",
  "^buttfuck$|^buttfucka$",
  "^buttfucker$|^buttfuckers$",
  "^butthead$",
  "^butthole$",
  "^buttman$",
  "^buttmuch$|^buttmunch$|^buttmuncher$",
  "^buttpirate$",
  "^buttplug$",
  "^buttstain$",
  "^buttwipe$",
  "^byatch$",
  "^c-0-c-k$|^c-o-c-k$",
  "^c-u-n-t$",
  "^c0ck$|^c0cks$|^c0k$|^c0cksucker$",
  "^cabron$",
  "^caca$",
  "^cacafuego$",
  "^cacker$",
  "^cahone$",
  "^camel jockey$",
  "^camel jockeys$",
  "^camel toe$",
  "^cameljockey$",
  "^cameltoe$",
  "^camgirl$",
  "^camslut$",
  "^camwhore$",
  "^carpet muncher$",
  "^carpetmuncher$",
  "^carruth$",
  "^cawk$",
  "^cawks$",
  "^cazzo$",
  "^cervix$",
  "^chav$",
  "^cheese eating surrender monkey$",
  "^cheese eating surrender monkies$",
  "^cheeseeating surrender monkey$",
  "^cheeseeating surrender monkies$",
  "^cheesehead$",
  "^cheeseheads$",
  "^cherrypopper$",
  "^chesticle$",
  "^chi-chi man$",
  "^chick with a dick$",
  "^chickslick$",
  "^child-fucker$",
  "^china swede$",
  "^china swedes$",
  "^chinaman$|^chinamen$",
  "^chinaswede$|^chinaswedes$",
  "^chinc$|^chincs$",
  "^ching chong$",
  "^ching chongs$",
  "^chinga$",
  "^chingchong$",
  "^chingchongs$",
  "^chink$|^chinks$|^chinky$",
  "^choad$|^choade$",
  "^choc ice$",
  "^chocolate rosebuds$",
  "^chode$|^chodes$",
  "^chonkies$|^chonky$|^chonkys$",
  "^chota bags$",
  "^chraa$",
  "^christ killer$|^christ killers$",
  "^chug$|^chugs$",
  "^chuj$",
  "^chunger$|^chungers$",
  "^chunkies$",
  "^chunkys$",
  "^chute$",
  "^cipa$",
  "^circlejerk$",
  "^cl1t$",
  "^clamdigger$",
  "^clamdiver$",
  "^clamps$",
  "^clansman$|^clansmen$|^clanswoman$|^clanswomen$",
  "^cleveland steamer$",
  "^climax$",
  "^clit$",
  "^clit licker$",
  "^clitface$|^clitfuck$",
  "^clitoris$|^clitorus$|^clits$",
  "^clitty$",
  "^clitty litter$",
  "^clogwog$",
  "^clover clamps$",
  "^clunge$",
  "^clusterfuck$",
  "^cnts$|^cntz$|^cnut$",
  "^cocain$|^cocaine$",
  "^coccydynia$",
  "^cock$",
  "^cock pocket$",
  "^cock snot$",
  "^cock sucker$",
  "^cock-head$",
  "^cock-sucker$",
  "^cockass$",
  "^cockbite$",
  "^cockblock$|^cockblocker$",
  "^cockburger$",
  "^cockcowboy$",
  "^cockeye$",
  "^cockface$",
  "^cockfight$",
  "^cockfucker$",
  "^cockfoam$",
  "^cockhead$",
  "^cockholster$",
  "^cockjockey$",
  "^cockknob$",
  "^cockknocker$",
  "^cockknoker$",
  "^cocklicker$",
  "^cocklump$",
  "^cocklover$",
  "^cockmaster$",
  "^cockmongler$",
  "^cockmongruel$",
  "^cockmonkey$",
  "^cockmunch$",
  "^cockmuncher$",
  "^cocknob$",
  "^cocknose$",
  "^cocknugget$",
  "^cockqueen$",
  "^cockrider$",
  "^cocks$",
  "^cockshit$",
  "^cocksman$",
  "^cocksmith$",
  "^cocksmoke$",
  "^cocksmoker$",
  "^cocksniffer$",
  "^cocksucer$",
  "^cocksuck$|^cocksucked$|^cocksucker$|^cocksuckers$",
  "^cocksucking$|^cocksucks$",
  "^cocksuka$",
  "^cocksukka$",
  "^cocktease$",
  "^cockwaffle$",
  "^cocky$",
  "^coffin dodger$",
  "^cohee$",
  "^coital$",
  "^coitus$",
  "^cok$",
  "^cokmuncher$",
  "^coksucka$",
  "^commie$",
  "^condom$",
  "^coochie$",
  "^coochy$",
  "^coolie$",
  "^coolies$",
  "^cooly$",
  "^coon$",
  "^coon ass$",
  "^coon asses$",
  "^coonass$|^coonasses$|^coonnass$",
  "^coondog$",
  "^coons$",
  "^cooter$",
  "^cop some wood$",
  "^coprolagnia$",
  "^coprophilia$",
  "^copulate$",
  "^corksucker$",
  "^cornhole$",
  "^corp whore$",
  "^corpulent$",
  "^cowgirl$",
  "^cox$",
  "^cra5h$",
  "^crabs$",
  "^crack$",
  "^crackcocain$",
  "^cracker$",
  "^crackpipe$",
  "^crackwhore$",
  "^crap$",
  "^crapola$",
  "^crapper$",
  "^crappy$",
  "^crash$",
  "^creampie$",
  "^cretin$",
  "^crikey$",
  "^cripple$",
  "^crotch$",
  "^crotchjockey$",
  "^crotchmonkey$",
  "^crotchrot$",
  "^crotte$",
  "^cum$",
  "^cum chugger$",
  "^cum dumpster$",
  "^cum freak$",
  "^cum guzzler$",
  "^cumbubble$",
  "^cumdump$",
  "^cumdumpster$",
  "^cumfest$",
  "^cumguzzler$",
  "^cumjockey$",
  "^cumm$",
  "^cummer$",
  "^cummin$",
  "^cumming$",
  "^cumquat$",
  "^cumqueen$",
  "^cums$",
  "^cumshot$",
  "^cumshots$",
  "^cumslut$",
  "^cumstain$",
  "^cumtart$",
  "^cunilingus$",
  "^cunillingus$",
  "^cunn$",
  "^cunnie$",
  "^cunnilingus$",
  "^cunntt$",
  "^cunny$",
  "^cunt$|^c u n t$",
  "^cunt hair$",
  "^cunt-struck$",
  "^cuntass$",
  "^cuntbag$",
  "^cunteyed$",
  "^cuntface$",
  "^cuntfuck$",
  "^cuntfucker$",
  "^cunthole$",
  "^cunthunter$",
  "^cuntlick$|^cuntlicker$|^cuntlicking$",
  "^cuntrag$",
  "^cunts$",
  "^cuntsicle$",
  "^cuntslut$",
  "^cuntsucker$",
  "^cuntz$",
  "^curry muncher$|^curry munchers$",
  "^currymuncher$|^currymunchers$",
  "^cushi$",
  "^cushis$",
  "^cut rope$",
  "^cyalis$",
  "^cyberfuc$|^cyberfuck",
  "^cybersex$",
  "^cyberslimer$",
  "^d0ng$",
  "^d0uch3$",
  "^d0uche$",
  "^d1ck$",
  "^d1ld0$",
  "^d1ldo$",
  "^d4mn$",
  "^dago$",
  "^dagos$",
  "^dahmer$",
  "^damm$",
  "^dammit$",
  "^damn$",
  "^damnation$",
  "^damned$",
  "^damnit$",
  "^darkey$",
  "^darkeys$",
  "^darkie$|^darkies$",
  "^darky$",
  "^darn$",
  "^date rape$",
  "^daterape$",
  "^datnigga$",
  "^dawgie style$",
  "^dawgie-style$",
  "^daygo$",
  "^deapthroat$",
  "^deep throat$",
  "^deep throating$",
  "^deepaction$",
  "^deepthroat$",
  "^deepthroating$",
  "^defecate$",
  "^deggo$",
  "^dego$",
  "^degos$",
  "^demon$",
  "^dendrophilia$",
  "^destroyyourpussy$",
  "^deth$",
  "^diaper head$",
  "^diaper heads$",
  "^diaperhead$",
  "^diaperheads$",
  "^dick$",
  "^dick head$",
  "^dick hole$",
  "^dick pic$",
  "^dick shy$",
  "^dick-ish$",
  "^dick-sneeze$",
  "^dickbag$",
  "^dickbeaters$",
  "^dickbrain$",
  "^dickdipper$",
  "^dickface$",
  "^dickflipper$",
  "^dickforbrains$",
  "^dickfuck$",
  "^dickfucker$",
  "^dickhead$",
  "^dickheads$",
  "^dickhole$",
  "^dickish$",
  "^dickjuice$",
  "^dickless$",
  "^dicklick$",
  "^dicklicker$",
  "^dickman$",
  "^dickmilk$",
  "^dickmonger$",
  "^dickpic$",
  "^dickripper$",
  "^dicks$",
  "^dicksipper$",
  "^dickslap$",
  "^dicksucker$",
  "^dicksucking$",
  "^dicktickler$",
  "^dickwad$",
  "^dickweasel$",
  "^dickweed$",
  "^dickwhipper$",
  "^dickwod$",
  "^dickzipper$",
  "^diddle$",
  "^dike$",
  "^dild0$",
  "^dild0s$",
  "^dildo$",
  "^dildos$",
  "^dilf$",
  "^diligaf$",
  "^dilld0$",
  "^dilld0s$",
  "^dillweed$",
  "^dimwit$",
  "^dingle$",
  "^dingleberries$",
  "^dingleberry$",
  "^dink$",
  "^dinks$",
  "^dipship$",
  "^dipshit$",
  "^dipstick$",
  "^dirsa$",
  "^dirty Sanchez$",
  "^dirty pillows$",
  "^dirty sanchez$",
  "^div$",
  "^dix$",
  "^dixiedike$",
  "^dixiedyke$",
  "^dlck$",
  "^dog style$",
  "^dog-fucker$",
  "^doggie$",
  "^doggie style$",
  "^doggie-style$",
  "^doggiestyle$",
  "^doggin$",
  "^dogging$",
  "^doggy style$",
  "^doggy-style$",
  "^doggystyle$",
  "^dolcett$",
  "^domination$",
  "^dominatricks$",
  "^dominatrics$",
  "^dominatrix$",
  "^dommes$",
  "^dong$",
  "^donkey punch$",
  "^donkeypunch$",
  "^donkeyribber$",
  "^doochbag$",
  "^doodoo$",
  "^doofus$",
  "^dookie$",
  "^doosh$",
  "^dopey$",
  "^dot head$",
  "^dot heads$",
  "^dothead$",
  "^dotheads$",
  "^double dong$",
  "^double penetration$",
  "^doubledong$",
  "^doublelift$",
  "^doublepenetration$",
  "^douch3$",
  "^douche$",
  "^douche bag$",
  "^douche-fag$",
  "^douchebag$",
  "^douchebags$",
  "^douchewaffle$",
  "^douchey$",
  "^dumbcunt$",
  "^dp$",
  "^dp action$",
  "^dpaction$",
  "^dragqueen$",
  "^dragqween$",
  "^dripdick$",
  "^drug$",
  "^dry hump$",
  "^dryhump$",
  "^duche$",
  "^dudette$",
  "^dumass$",
  "^dumb ass$",
  "^dumbass$",
  "^dumbasses$",
  "^dumbbitch$",
  "^dumbfuck$",
  "^dumbshit$",
  "^dummy$",
  "^dumshit$",
  "^dune coon$",
  "^dune coons$",
  "^dupa$",
  "^dvda$",
  "^dyefly$",
  "^dyke$",
  "^dykes$",
  "^dziwka$",
  "^earotics$",
  "^easyslut$",
  "^eat a dick$",
  "^eat hair pie$",
  "^eat my$",
  "^eat my ass$",
  "^eatballs$",
  "^eatme$",
  "^eatmyass$",
  "^eatpussy$",
  "^ecchi$",
  "^ejackulate$",
  "^ejaculate$",
  "^ejaculated$",
  "^ejaculates$",
  "^ejaculating$",
  "^ejaculatings$",
  "^ejaculation$",
  "^ejaculations$",
  "^ejakulate$",
  "^ekrem$",
  "^ekto$",
  "^enculer$",
  "^enema$",
  "^enlargement$",
  "^erect$",
  "^erection$",
  "^ero$",
  "^erotic$",
  "^erotism$",
  "^escort$",
  "^esqua$",
  "^essohbee$",
  "^ethical slut$",
  "^eunuch$",
  "^evl$",
  "^excrement$",
  "^exkwew$",
  "^explosion$",
  "^extacy$",
  "^extasy$",
  "^f u c k$",
  "^f u c k e$",
  "^f u c k e r$",
  "^f u k$",
  "^f-u-c-k$",
  "^f4nny$",
  "^f_u_c_k$",
  "^facefucker$",
  "^facial$",
  "^fack$",
  "^faeces$",
  "^faen$",
  "^fag$",
  "^fag1t$",
  "^fagbag$",
  "^faget$",
  "^fagfucker$",
  "^fagg",
  "^fagg1t$",
  "^fagit$",
  "^fagot$",
  "^fagots$",
  "^fags$",
  "^fagt$",
  "^fagtard$",
  "^fagz$",
  "^faig$",
  "^faigs$",
  "^faigt$",
  "^fanculo$",
  "^fanny$",
  "^fannybandit$",
  "^fannyflaps$",
  "^fannyfucker$",
  "^fanyy$",
  "^fartknocker$",
  "^farty$",
  "^fastfuck$",
  "^fatah$",
  "^fatass$",
  "^fatfuck$",
  "^fatfucker$",
  "^fatso$",
  "^fck$",
  "^fckcum$",
  "^fckd$",
  "^fcuk$",
  "^fcuker$",
  "^fcuking$",
  "^fecal$",
  "^feces$",
  "^feck$",
  "^fecker$",
  "^feg$",
  "^feist$",
  "^felatio$",
  "^felch$",
  "^felcher$",
  "^felching$",
  "^fellate$",
  "^fellatio$",
  "^feltch$",
  "^feltcher$",
  "^feltching$",
  "^female squirting$",
  "^femalesquirtin$",
  "^femalesquirting$",
  "^femdom$",
  "^fenian$",
  "^fetish$",
  "^fice$",
  "^ficken$",
  "^figging$",
  "^fingerbang$",
  "^fingerfood$",
  "^fingerfuck",
  "^fingering$",
  "^fist fuck$",
  "^fisted$",
  "^fister$",
  "^fistfuck",
  "^fisting$",
  "^fisty$",
  "^fitt$",
  "^flamer$",
  "^flange$",
  "^flaps$",
  "^flasher$",
  "^fleshflute$",
  "^flikker$",
  "^flipping the bird$",
  "^flog the log$",
  "^floo$",
  "^floozy$",
  "^flydie$",
  "^flydye$",
  "^foad$",
  "^foah$",
  "^fok$",
  "^fondle$",
  "^foobar$",
  "^fook$",
  "^fooker$",
  "^foot fetish$",
  "^footaction$",
  "^footfetish$",
  "^footfuck$",
  "^footfucker$",
  "^footjob$",
  "^footlicker$",
  "^footstar$",
  "^foreskin$",
  "^forni$",
  "^fornicate$",
  "^fotze$",
  "^foursome$",
  "^fourtwenty$",
  "^freakfuck$",
  "^freakyfucker$",
  "^freefuck$",
  "^freex$",
  "^frenchify$",
  "^frigg$",
  "^frigga$",
  "^frotting$",
  "^fubar$",
  "^fuc$",
  "^fucck$",
  "^fuck$",
  "^fucks$",
  "^fuck buttons$",
  "^fuck hole$",
  "^fuck puppet$",
  "^fuck trophy$",
  "^fuck yo mama$",
  "^fuck you$",
  "^fuck-ass$",
  "^fuck-bitch$",
  "^fuck-tard$",
  "^fucksoff$",
  "^fucka$",
  "^fuckable$",
  "^fuckass$",
  "^fuckbag$",
  "^fuckbook$",
  "^fuckboy$",
  "^fuckbrain$",
  "^fuckbuddy$",
  "^fuckbutt$",
  "^fuckbutter$",
  "^fuckd$",
  "^fucked$",
  "^fuckedup$",
  "^fucker$",
  "^fuckers$",
  "^fuckersucker$",
  "^fuckface$",
  "^fuckfest$",
  "^fuckfreak$",
  "^fuckfriend$",
  "^fuckhead$",
  "^fuckheads$",
  "^fuckher$",
  "^fuckhole$",
  "^fuckin$",
  "^fuckina$",
  "^fucking$",
  "^fuckingbitch$",
  "^fuckings$",
  "^fuckingshitmotherfucker$",
  "^fuckinnuts$",
  "^fuckinright$",
  "^fuckit$",
  "^fuckknob$",
  "^fuckme$",
  "^fuckmeat$",
  "^fuckmehard$",
  "^fuckmonkey$",
  "^fuckn$",
  "^fucknugget$",
  "^fucknut$",
  "^fucknuts$",
  "^fucknutt$",
  "^fucknutz$",
  "^fuckoff$",
  "^fuckpig$",
  "^fuckr$",
  "^fucks$",
  "^fuckstick$",
  "^fucktard$",
  "^fucktards$",
  "^fucktart$",
  "^fucktoy$",
  "^fucktwat$",
  "^fuckup$",
  "^fuckwad$",
  "^fuckwhit$",
  "^fuckwhore$",
  "^fuckwit$",
  "^fuckwitt$",
  "^fuckyou$",
  "^fudge packer$",
  "^fudge-packer$",
  "^fudgepacker$",
  "^fugly$",
  "^fuk$",
  "^fukah$",
  "^fuken$",
  "^fuker$",
  "^fukin$",
  "^fuking$",
  "^fukk$",
  "^fukkah$",
  "^fukken$",
  "^fukker$",
  "^fukkers$",
  "^fukkin$",
  "^fuks$",
  "^fuktard$",
  "^fuktards$",
  "^fukwhit$",
  "^fukwit$",
  "^funeral$",
  "^funfuck$",
  "^fungus$",
  "^fuq$",
  "^futanari$",
  "^futkretzn$",
  "^fuuck$",
  "^fux$",
  "^fux0r$",
  "^fvck$",
  "^fvk$",
  "^fxck$",
  "^g-spot$",
  "^g00k$",
  "^gae$",
  "^gai$",
  "^gang bang$",
  "^gang-bang$",
  "^gangbang",
  "^gangsta$",
  "^ganja$",
  "^gash$",
  "^gassy ass$",
  "^gator bait$",
  "^gatorbait$",
  "^gay sex$",
  "^gayass$",
  "^gaybob$",
  "^gayboy$",
  "^gaydo$",
  "^gayfuck$",
  "^gayfuckist$",
  "^gaygirl$",
  "^gaylord$",
  "^gaymuthafuckinwhore$",
  "^gays$",
  "^gaysex$",
  "^gaytard$",
  "^gaywad$",
  "^gayz$",
  "^geezer$",
  "^gender bender$",
  "^geni$",
  "^genital$",
  "^genitals$",
  "^getiton$",
  "^gey$",
  "^gfy$",
  "^ghay$",
  "^ghey$",
  "^giant cock$",
  "^gigolo$",
  "^ginger$",
  "^ginzo$",
  "^ginzos$",
  "^gipp$",
  "^gippo$",
  "^gippos$",
  "^gipps$",
  "^girl on$",
  "^girl on top$",
  "^girls gone wild$",
  "^givehead$",
  "^glans$",
  "^glazeddonut$",
  "^goatcx$",
  "^goatse$",
  "^gob$",
  "^god dammit$",
  "^god damn$",
  "^god damnit$",
  "^god-dam$",
  "^god-damned$",
  "^godam$",
  "^godammit$",
  "^godamn$",
  "^godamnit$",
  "^goddam",
  "^godsdamn$",
  "^gokkun$",
  "^golden shower$",
  "^goldenshower$",
  "^golliwog$",
  "^golliwogs$",
  "^gonad$",
  "^gonads$",
  "^gonorrehea$",
  "^gonzagas$",
  "^goo girl$",
  "^gooch$",
  "^goodpoop$",
  "^gook$",
  "^gook eye$",
  "^gook eyes$",
  "^gookeye$",
  "^gookeyes$",
  "^gookies$",
  "^gooks$",
  "^gooky$",
  "^gora$",
  "^goras$",
  "^goregasm$",
  "^gotohell$",
  "^goy$",
  "^goyim$",
  "^greaseball$",
  "^greaseballs$",
  "^gringo$",
  "^gringos$",
  "^groe$",
  "^groid$",
  "^groids$",
  "^grope$",
  "^gross$",
  "^grostulation$",
  "^group sex$",
  "^gspot$",
  "^gstring$",
  "^gtfo$",
  "^gub$",
  "^gubba$",
  "^gubbas$",
  "^gubs$",
  "^guido$",
  "^guiena$",
  "^guineas$",
  "^guizi$",
  "^gummer$",
  "^guro$",
  "^gwailo$",
  "^gwailos$",
  "^gweilo$",
  "^gweilos$",
  "^gyopo$",
  "^gyopos$",
  "^gyp$",
  "^gyped$",
  "^gypo$",
  "^gypos$",
  "^gypp",
  "^gypsys$",
  "^h e l l$",
  "^h o m$",
  "^h00r$",
  "^h0ar$",
  "^h0m0$",
  "^h0mo$",
  "^h0r$",
  "^h0re$",
  "^h4x0r$",
  "^hadji$",
  "^hadjis$",
  "^hairyback$",
  "^hairybacks$",
  "^haji$",
  "^hajis$",
  "^hajji$",
  "^hajjis$",
  "^half breed$",
  "^half caste$",
  "^halfbreed$",
  "^halfcaste$",
  "^ham flap$",
  "^hamas$",
  "^hand job$",
  "^handjob$",
  "^haole$",
  "^haoles$",
  "^hapa$",
  "^hard core$",
  "^hard on$",
  "^hardcore$",
  "^hardcoresex$",
  "^hardon$",
  "^harem$",
  "^he-she$",
  "^he11$",
  "^headass$",
  "^headfuck$",
  "^hebe$",
  "^hebes$",
  "^heeb$",
  "^heebs$",
  "^hell$",
  "^hells$",
  "^helvete$",
  "^hemp$",
  "^henhouse$",
  "^hentai$",
  "^heroin$",
  "^herp$",
  "^herpes$",
  "^herpy$",
  "^heshe$",
  "^hijacker$",
  "^hijacking$",
  "^hillbillies$",
  "^hillbilly$",
  "^hindoo$",
  "^hircismus$",
  "^hiscock$",
  "^hitler$",
  "^hitlerism$",
  "^hitlerist$",
  "^hiv$",
  "^ho$",
  "^hoar$",
  "^hoare$",
  "^hobag$",
  "^hodgie$",
  "^hoe$",
  "^hoer$",
  "^hoes$",
  "^holestuffer$",
  "^holy shit$",
  "^hom0$",
  "^homey$",
  "^homicide$",
  "^homo$",
  "^homobangers$",
  "^homodumbshit$",
  "^homoerotic$",
  "^homoey$",
  "^honger$",
  "^honkers$",
  "^honkey$",
  "^honkeys$",
  "^honkie$",
  "^honkies$",
  "^honky$",
  "^hooch$",
  "^hookah$",
  "^hooker$",
  "^hookers$",
  "^hoor$",
  "^hoore$",
  "^hootch$",
  "^hooter$",
  "^hooters$",
  "^hore$",
  "^hori$",
  "^horis$",
  "^hork$",
  "^horndawg$",
  "^horndog$",
  "^horney$",
  "^horniest$",
  "^horny$",
  "^horseshit$",
  "^hosejob$",
  "^hoser$",
  "^hot carl$",
  "^hot chick$",
  "^hotcarl$",
  "^hotdamn$",
  "^hotpussy$",
  "^hotsex$",
  "^hottotrot$",
  "^how to kill$",
  "^how to murdep$",
  "^how to murder$",
  "^huevon$",
  "^huge fat$",
  "^hugefat$",
  "^hui$",
  "^hummer$",
  "^hump$",
  "^humped$",
  "^humper$",
  "^humpher$",
  "^humphim$",
  "^humpin$",
  "^humping$",
  "^hun$",
  "^husky$",
  "^hussy$",
  "^hustler$",
  "^hymen$",
  "^hymie$",
  "^hymies$",
  "^iap$",
  "^iberian slap$",
  "^iblowu$",
  "^ike$",
  "^ikes$",
  "^ikey$",
  "^ikeymo$",
  "^ikeymos$",
  "^ikwe$",
  "^illegal$",
  "^illegals$",
  "^inbred$",
  "^incest$",
  "^indon$",
  "^indons$",
  "^injun$",
  "^injuns$",
  "^insest$",
  "^intercourse$",
  "^interracial$",
  "^intheass$",
  "^inthebuff$",
  "^israels$",
  "^j3rk0ff$",
  "^jack off$",
  "^jack-off$",
  "^jackass$",
  "^jackasses$",
  "^jackhole$",
  "^jackoff$",
  "^jackshit$",
  "^jacktheripper$",
  "^jaggi$",
  "^jagoff$",
  "^jail bait$",
  "^jailbait$",
  "^jap$",
  "^japcrap$",
  "^japie$",
  "^japies$",
  "^japs$",
  "^jebus$",
  "^jelly donut$",
  "^jerk$",
  "^jerk off$",
  "^jerk-off$",
  "^jerk0ff$",
  "^jerkass$",
  "^jerked$",
  "^jerkoff$",
  "^jerries$",
  "^jerry$",
  "^jesuschrist$",
  "^jewed$",
  "^jewess$",
  "^jig$",
  "^jiga$",
  "^jigaboo$",
  "^jigaboos$",
  "^jigarooni$",
  "^jigaroonis$",
  "^jigg",
  "^jigs$",
  "^jihad$",
  "^jijjiboo$",
  "^jijjiboos$",
  "^jimfish$",
  "^jisim$",
  "^jism$",
  "^jiss$",
  "^jiz$",
  "^jizim$",
  "^jizin$",
  "^jizjuice$",
  "^jizm$",
  "^jizn$",
  "^jizz$",
  "^jizzd$",
  "^jizzed$",
  "^jizzim$",
  "^jizzin$",
  "^jizzn$",
  "^jizzum$",
  "^jock$",
  "^jugg$",
  "^juggs$",
  "^jugs$",
  "^jungle bunnies$",
  "^jungle bunny$",
  "^junglebunny$",
  "^junkie$",
  "^junky$",
  "^kacap$",
  "^kacapas$",
  "^kacaps$",
  "^kaffer$",
  "^kaffir$",
  "^kaffre$",
  "^kafir$",
  "^kanake$",
  "^kanker$",
  "^katsap$",
  "^katsaps$",
  "^kawk$",
  "^khokhol$",
  "^khokhols$",
  "^kicking$",
  "^kigger$",
  "^kike$",
  "^kikes$",
  "^killer$",
  "^kills$",
  "^kimchis$",
  "^kinbaku$",
  "^kink$",
  "^kinkster$",
  "^kinky$",
  "^kinky Jesus$",
  "^kissass$",
  "^kkk$",
  "^klan$",
  "^klansman$",
  "^klansmen$",
  "^klanswoman$",
  "^klanswomen$",
  "^klootzak$",
  "^knob$",
  "^knob end$",
  "^knobbing$",
  "^knobead$",
  "^knobed$",
  "^knobend$",
  "^knobhead$",
  "^knobjocky$",
  "^knobjokey$",
  "^knobz$",
  "^knockers$",
  "^knulle$",
  "^kock$",
  "^kondum$",
  "^kondums$",
  "^kooch$",
  "^kooches$",
  "^koon$",
  "^kootch$",
  "^krap$",
  "^krappy$",
  "^kraut$",
  "^krauts$",
  "^kuffar$",
  "^kuk$",
  "^kuksuger$",
  "^kum$",
  "^kumbubble$",
  "^kumbullbe$",
  "^kumer$",
  "^kummer$",
  "^kumming$",
  "^kumquat$",
  "^kums$",
  "^kunilingus$",
  "^kunja$",
  "^kunnilingus$",
  "^kunt$",
  "^kunts$",
  "^kuntz$",
  "^kurac$",
  "^kurwa$",
  "^kushi$",
  "^kushis$",
  "^kusi$",
  "^kwa$",
  "^kwai lo$",
  "^kwai los$",
  "^kwif$",
  "^ky$",
  "^kyke$",
  "^kykes$",
  "^kyopo$",
  "^kyopos$",
  "^kyrpa$",
  "^l3itch$",
  "^labia$",
  "^ladies chest$",
  "^lady chest$",
  "^lameass$",
  "^lapdance$",
  "^lardass$",
  "^lds$",
  "^leather restraint$",
  "^leather straight$",
  "^leather straight jacket$",
  "^leatherrestraint$",
  "^lebo$",
  "^lebos$",
  "^lech$",
  "^len$",
  "^lemon party$",
  "^lemonparty$",
  "^leper$",
  "^lesbain$",
  "^lesbayn$",
  "^lesbian$",
  "^lesbin$",
  "^lesbo$",
  "^lesbos$",
  "^lez$",
  "^lezbe$",
  "^lezbefriends$",
  "^lezbian$",
  "^lezbians$",
  "^lezbo$",
  "^lezbos$",
  "^lezz$",
  "^lezzalesbo$",
  "^lezzian$",
  "^lezzie$",
  "^lezzies$",
  "^lezzo$",
  "^lezzy$",
  "^libido$",
  "^licker$",
  "^licking$",
  "^lickme$",
  "^lilniglet$",
  "^limey$",
  "^limpdick$",
  "^limy$",
  "^lingerie$",
  "^lipshits$",
  "^lipshitz$",
  "^livesex$",
  "^lmfao$",
  "^loadedgun$",
  "^loin$",
  "^loins$",
  "^lolita$",
  "^looney$",
  "^lovebone$",
  "^lovegoo$",
  "^lovegun$",
  "^lovejuice$",
  "^lovemaking$",
  "^lovemuscle$",
  "^lovepistol$",
  "^loverocket$",
  "^lowlife$",
  "^lsd$",
  "^lube$",
  "^lubejob$",
  "^lubra$",
  "^lucifer$",
  "^luckycammeltoe$",
  "^lugan$",
  "^lugans$",
  "^lust$",
  "^lusting$",
  "^lusty$",
  "^lynch$",
  "^m-fucking$",
  "^m0f0$",
  "^m0fo$",
  "^m45terbate$",
  "^ma5terb8$",
  "^ma5terbate$",
  "^mabuno$",
  "^mabunos$",
  "^macaca$",
  "^macacas$",
  "^mafugly$",
  "^magicwand$",
  "^mahbuno$",
  "^mahbunos$",
  "^make me come$",
  "^makemecome$",
  "^makemecum$",
  "^male squirting$",
  "^mamhoon$",
  "^mams$",
  "^manhater$",
  "^manpaste$",
  "^maricon$",
  "^marijuana$",
  "^masochist$",
  "^masokist$",
  "^massa$",
  "^massterbait$",
  "^masstrbait$",
  "^masstrbate$",
  "^mastabate$",
  "^mastabater$",
  "^master-bate$",
  "^masterb8$",
  "^masterbaiter$",
  "^masterbat",
  "^masterblaster$",
  "^mastrabator$",
  "^masturbat$",
  "^masturbate$",
  "^masturbating$",
  "^masturbation$",
  "^mattressprincess$",
  "^mau mau$",
  "^mau maus$",
  "^maumau$",
  "^maumaus$",
  "^maxi$",
  "^mcfagget$",
  "^meatbeatter$",
  "^meatrack$",
  "^menage$",
  "^menage a trois$",
  "^menses$",
  "^menstruate$",
  "^menstruation$",
  "^merd$",
  "^meth$",
  "^mgger$",
  "^mggor$",
  "^mibun$",
  "^mick$",
  "^mickeyfinn$",
  "^microphallus$",
  "^middle finger$",
  "^mideast$",
  "^midget$",
  "^mierda$",
  "^milf$",
  "^minge$",
  "^minger$",
  "^missionary$",
  "^missionary position$",
  "^mo-fo$",
  "^mockey$",
  "^mockie$",
  "^mocky$",
  "^mof0$",
  "^mofo$",
  "^moky$",
  "^molest$",
  "^molestation$",
  "^molester$",
  "^molestor$",
  "^moneyshot$",
  "^mong$",
  "^monkleigh$",
  "^moo moo foo foo$",
  "^moolie$",
  "^moon cricket$",
  "^moon crickets$",
  "^mooncricket$",
  "^mooncrickets$",
  "^mormon$",
  "^moron$",
  "^moskal$",
  "^moskals$",
  "^moslem$",
  "^mosshead$",
  "^motha fucker$",
  "^motha fuker$",
  "^motha fukkah$",
  "^motha fukker$",
  "^mothafuck",
  "^mother fucker$",
  "^mother fukah$",
  "^mother fuker$",
  "^mother fukkah$",
  "^mother fukker$",
  "^mother-fucker$",
  "^motherfuck",
  "^motherfvcker$",
  "^motherlovebone$",
  "^mothrfucker$",
  "^mouliewop$",
  "^mound of venus$",
  "^moundofvenus$",
  "^mr hands$",
  "^mrhands$",
  "^mtherfucker$",
  "^mthrfuck$",
  "^mthrfucker$",
  "^mthrfucking$",
  "^mtrfck$",
  "^mtrfuck$",
  "^mtrfucker$",
  "^mu therfucker$",
  "^muff$",
  "^muff diver$",
  "^muff puff$",
  "^muffdive$",
  "^muffdiver$",
  "^muffdiving$",
  "^muffindiver$",
  "^mufflikcer$",
  "^muie$",
  "^mulatto$",
  "^mulkku$",
  "^muncher$",
  "^munging$",
  "^munt$",
  "^munter$",
  "^murder$",
  "^murderer$",
  "^muschi$",
  "^mutha$",
  "^mutha fucker$",
  "^mutha fukah$",
  "^mutha fuker$",
  "^mutha fukkah$",
  "^mutha fukker$",
  "^muthafecker$",
  "^muthafuckaz$",
  "^muthafucker$",
  "^muthafuckker$",
  "^muther$",
  "^mutherfucker$",
  "^mutherfucking$",
  "^muthrfucking$",
  "^mzungu$",
  "^mzungus$",
  "^n1gga$",
  "^n1gger$",
  "^n1gr$",
  "^nad$",
  "^nads$",
  "^naked$",
  "^nambla$",
  "^napalm$",
  "^nappy$",
  "^nastt$",
  "^nasty$",
  "^nastybitch$",
  "^nastyho$",
  "^nastyslut$",
  "^nastywhore$",
  "^nawashi$",
  "^nazi$",
  "^nazis$",
  "^nazism$",
  "^necro$",
  "^need the dick$",
  "^negres$",
  "^negress$",
  "^negro$",
  "^negroes$",
  "^negroid$",
  "^negros$",
  "^neonazi$",
  "^nepesaurio$",
  "^nig$",
  "^nig nog$",
  "^nig-nog$",
  "^niga$",
  "^nigaboo$",
  "^nigar$",
  "^nigars$",
  "^nigas$",
  "^niger$",
  "^nigerian$",
  "^nigerians$",
  "^nigers$",
  "^nigette$",
  "^nigettes$",
  "^nigg$",
  "^nigg3r$",
  "^nigg4h$",
  "^nigga$",
  "^niggah$",
  "^niggahs$",
  "^niggar$",
  "^niggaracci$",
  "^niggard$",
  "^niggarded$",
  "^niggarding$",
  "^niggardliness$",
  "^niggardlinesss$",
  "^niggardly$",
  "^niggards$",
  "^niggars$",
  "^niggas$",
  "^niggaz$",
  "^nigger$",
  "^niggerhead$",
  "^niggerhole$",
  "^niggers$",
  "^niggle$",
  "^niggled$",
  "^niggles$",
  "^niggling$",
  "^nigglings$",
  "^niggor$",
  "^niggress$",
  "^niggresses$",
  "^nigguh$",
  "^nigguhs$",
  "^niggur$",
  "^niggurs$",
  "^niglet$",
  "^nignog$",
  "^nigor$",
  "^nigors$",
  "^nigr$",
  "^nigra$",
  "^nigras$",
  "^nigre$",
  "^nigres$",
  "^nigress$",
  "^nigs$",
  "^nigur$",
  "^niiger$",
  "^niigr$",
  "^nimphomania$",
  "^nimrod$",
  "^ninny$",
  "^ninnyhammer$",
  "^nip$",
  "^nipple$",
  "^nipplering$",
  "^nipples$",
  "^nips$",
  "^nittit$",
  "^nlgger$",
  "^nlggor$",
  "^nob$",
  "^nob jokey$",
  "^nobhead$",
  "^nobjocky$",
  "^nobjokey$",
  "^nofuckingway$",
  "^nog$",
  "^nonce$",
  "^nookey$",
  "^nookie$",
  "^nooky$",
  "^noonan$",
  "^nooner$",
  "^nsfw$",
  "^nsfw images$",
  "^nude$",
  "^nudger$",
  "^nudie$",
  "^nudies$",
  "^nudity$",
  "^numbnuts$",
  "^nut butter$",
  "^nut sack$",
  "^nutfucker$",
  "^nutsack$",
  "^nutter$",
  "^nymph$",
  "^nympho$",
  "^nymphomania$",
  "^o c k$",
  "^octopussy$",
  "^old bag$",
  "^omorashi$",
  "^one cup two girls$",
  "^one guy$",
  "^one guy one jar$",
  "^one jar$",
  "^ontherag$",
  "^opiate$",
  "^opium$",
  "^orafis$",
  "^oral$",
  "^orally$",
  "^orga$",
  "^orgasim$",
  "^orgasim$",
  "^orgasims$",
  "^orgasm$",
  "^orgasmic$",
  "^orgasms$",
  "^orgasum$",
  "^orgies$",
  "^orgy$",
  "^oriface$",
  "^orifice$",
  "^orifiss$",
  "^orospu$",
  "^osama$",
  "^ovary$",
  "^ovum$",
  "^ovums$",
  "^p e n i s$",
  "^p i s$",
  "^p u s s y$",
  "^p0rn$",
  "^packi$",
  "^packie$",
  "^packy$",
  "^paddy$",
  "^paedo$",
  "^paedoman$",
  "^paedophile$",
  "^paki$",
  "^pakie$",
  "^pakis$",
  "^paky$",
  "^palesimian$",
  "^pancake face$",
  "^pancake faces$",
  "^panooch$",
  "^pansies$",
  "^pansy$",
  "^panti$",
  "^pantie$",
  "^panties$",
  "^panty$",
  "^paska$",
  "^pastie$",
  "^pasty$",
  "^pawn$",
  "^payo$",
  "^pcp$",
  "^pearlnecklace$",
  "^peck$",
  "^pecker$",
  "^peckerhead$",
  "^peckerwood$",
  "^pedo$",
  "^pedobear$",
  "^pedoman$",
  "^pedophile$",
  "^pedophilia$",
  "^pedophiliac$",
  "^pee$",
  "^peeenus$",
  "^peeenusss$",
  "^peehole$",
  "^peenus$",
  "^peepee$",
  "^peepshow$",
  "^peepshpw$",
  "^pegging$",
  "^peinus$",
  "^pen1s$",
  "^penas$",
  "^pendejo$",
  "^pendy$",
  "^penetrate$",
  "^penetration$",
  "^peni5$",
  "^penial$",
  "^penile$",
  "^penis$",
  "^penis-breath$",
  "^penisbanger$",
  "^penises$",
  "^penisfucker$",
  "^penisland$",
  "^penislick$",
  "^penislicker$",
  "^penispuffer$",
  "^penthouse$",
  "^penus$",
  "^penuus$",
  "^perse$",
  "^perv$",
  "^perversion$",
  "^peyote$",
  "^phalli$",
  "^phallic$",
  "^phone sex$",
  "^phonesex$",
  "^phuc$",
  "^phuck$",
  "^phuk$",
  "^phuked$",
  "^phuker$",
  "^phuking$",
  "^phukked$",
  "^phukker$",
  "^phukking$",
  "^phuks$",
  "^phungky$",
  "^phuq$",
  "^pi55$",
  "^picaninny$",
  "^piccaninny$",
  "^picka$",
  "^pickaninnies$",
  "^pickaninny$",
  "^piece of shit$",
  "^pieceofshit$",
  "^piefke$",
  "^piefkes$",
  "^pierdol$",
  "^pigfucker$",
  "^piker$",
  "^pikey$",
  "^piky$",
  "^pillowbiter$",
  "^pillu$",
  "^pimmel$",
  "^pimp$",
  "^pimped$",
  "^pimper$",
  "^pimpis$",
  "^pimpjuic$",
  "^pimpjuice$",
  "^pimpsimp$",
  "^pindick$",
  "^pinko$",
  "^pis$",
  "^pises$",
  "^pisin$",
  "^pising$",
  "^pisof$",
  "^piss$",
  "^piss off$",
  "^piss pig$",
  "^piss-off$",
  "^pissed$",
  "^pissed off$",
  "^pisser$",
  "^pissers$",
  "^pisses$",
  "^pissflaps$",
  "^pisshead$",
  "^pissin$",
  "^pissing$",
  "^pissoff$",
  "^pisspig$",
  "^pistol$",
  "^pizda$",
  "^playboy$",
  "^playgirl$",
  "^pleasure chest$",
  "^pleasurechest$",
  "^pms$",
  "^pocha$",
  "^pochas$",
  "^pocho$",
  "^pochos$",
  "^pocketpool$",
  "^pohm$",
  "^pohms$",
  "^polac$",
  "^polack$",
  "^polacks$",
  "^polak$",
  "^pole smoker$",
  "^polesmoker$",
  "^pollock$",
  "^pollocks$",
  "^pommie$",
  "^pommie grant$",
  "^pommie grants$",
  "^pommies$",
  "^pommy$",
  "^ponyplay$",
  "^poo$",
  "^poof$",
  "^poon$",
  "^poonani$",
  "^poonany$",
  "^poontang$",
  "^poontsee$",
  "^poop$",
  "^poop chute$",
  "^poopchute$",
  "^pooper$",
  "^poopuncher$",
  "^pooperscooper$",
  "^pooping$",
  "^poorwhitetrash$",
  "^popimp$",
  "^porch monkey$",
  "^porch monkies$",
  "^porchmonkey$",
  "^porn$",
  "^pornflick$",
  "^pornking$",
  "^porno$",
  "^pornography$",
  "^pornos$",
  "^pornprincess$",
  "^pound town$",
  "^poundtown$",
  "^pplicker$",
  "^pr0n$",
  "^pr1c$",
  "^pr1ck$",
  "^pr1k$",
  "^prairie nigger$",
  "^prairie niggers$",
  "^premature$",
  "^preteen$",
  "^pric$",
  "^prick$",
  "^prickhead$",
  "^pricks$",
  "^prickteaser$",
  "^prig$",
  "^prince albert piercing$",
  "^prod$",
  "^pron$",
  "^propaganda$",
  "^prostitute$",
  "^prude$",
  "^psycho$",
  "^pthc$",
  "^pu55i$",
  "^pu55y$",
  "^pube$",
  "^pubes$",
  "^pubic$",
  "^pubiclice$",
  "^pubis$",
  "^pud$",
  "^pudboy$",
  "^pudd$",
  "^puddboy$",
  "^puke$",
  "^pula$",
  "^pule$",
  "^punani$",
  "^punanny$",
  "^punany$",
  "^punkass$",
  "^punky$",
  "^punta$",
  "^puntang$",
  "^purinapricness$",
  "^pusies$",
  "^puss$",
  "^pusse$",
  "^pussee$",
  "^pussi$",
  "^pussie$",
  "^pussies$",
  "^pussy$",
  "^pussy fart$",
  "^pussy palace$",
  "^pussycat$",
  "^pussydestroyer$",
  "^pussyeater$",
  "^pussyfucker$",
  "^pussylicker$",
  "^pussylicking$",
  "^pussylips$",
  "^pussylover$",
  "^pussypounder$",
  "^pussys$",
  "^pust$",
  "^pusy$",
  "^puta$",
  "^puto$",
  "^puuke$",
  "^puuker$",
  "^qahbeh$",
  "^quashie$",
  "^queaf$",
  "^queef$",
  "^queer$",
  "^queerbait$",
  "^queerhole$",
  "^queero$",
  "^queers$",
  "^queerz$",
  "^quickie$",
  "^quicky$",
  "^quiff$",
  "^quim$",
  "^qweers$",
  "^qweerz$",
  "^qweir$",
  "^r-tard$",
  "^r-tards$",
  "^r5e$",
  "^ra8s$",
  "^racial$",
  "^racy$",
  "^radicals$",
  "^raghead$",
  "^ragheads$",
  "^raging$",
  "^raging boner$",
  "^ragingboner$",
  "^randy$",
  "^rape$",
  "^raped$",
  "^raper$",
  "^rapey$",
  "^raping$",
  "^rapist$",
  "^raunch$",
  "^rautenberg$",
  "^rearend$",
  "^rearentry$",
  "^recktum$",
  "^rectal$",
  "^rectum$",
  "^rectus$",
  "^redleg$",
  "^redlegs$",
  "^redlight$",
  "^redneck$",
  "^rednecks$",
  "^redskin$",
  "^redskins$",
  "^reefer$",
  "^reestie$",
  "^reetard$",
  "^refugee$",
  "^reich$",
  "^renob$",
  "^rentafuck$",
  "^rere$",
  "^retard$",
  "^retarded$",
  "^retards$",
  "^retardz$",
  "^reverse cowgirl$",
  "^reversecowgirl$",
  "^revue$",
  "^rigger$",
  "^rimjaw$",
  "^rimjob$",
  "^rimming$",
  "^ritard$",
  "^rosebuds$",
  "^rosy palm$",
  "^rosy palm and her 5 sisters$",
  "^rosypalm$",
  "^rosypalmandher5sisters$",
  "^rosypalmandherefivesisters$",
  "^round eyes$",
  "^roundeye$",
  "^roundhead$",
  "^rtard$",
  "^rtards$",
  "^rubbish$",
  "^rump$",
  "^rumprammer$",
  "^ruski$",
  "^russki$",
  "^russkie$",
  "^rusty trombone$",
  "^rustytrombone$",
  "^s h i t$",
  "^s hit$",
  "^ssm$",
  "^s-h-1-t$",
  "^s-h-i-t$",
  "^s-o-b$",
  "^s0b$",
  "^s_h_i_t$",
  "^sac$",
  "^sack$",
  "^sadis$",
  "^sadism$",
  "^sadist$",
  "^sadom$",
  "^sambo$",
  "^sambos$",
  "^samckdaddy$",
  "^sanchez$",
  "^sand nigger$",
  "^sand niggers$",
  "^sandbar$",
  "^sandm$",
  "^sandler$",
  "^sandnigger$",
  "^sanger$",
  "^santorum$",
  "^sausage queen$",
  "^scag$",
  "^scallywag$",
  "^scank$",
  "^scantily$",
  "^scat$",
  "^schaffer$",
  "^scheiss$",
  "^schizo$",
  "^schlampe$",
  "^schlong$",
  "^schmuck$",
  "^schvartse$",
  "^schvartsen$",
  "^schwartze$",
  "^schwartzen$",
  "^scissoring$",
  "^screwed$",
  "^screwing$",
  "^screwyou$",
  "^scroat$",
  "^scrog$",
  "^scrot$",
  "^scrote$",
  "^scrotum$",
  "^scrud$",
  "^scum$",
  "^seaman$",
  "^seamen$",
  "^seduce$",
  "^seks$",
  "^semen$",
  "^seppo$",
  "^seppos$",
  "^septics$",
  "^sex$",
  "^sexed$",
  "^sexfarm$",
  "^sexhound$",
  "^sexhouse$",
  "^sexi$",
  "^sexing$",
  "^sexkitten$",
  "^sexo$",
  "^sexpot$",
  "^sexslave$",
  "^sextogo$",
  "^sextoy$",
  "^sextoys$",
  "^sexual$",
  "^sexually$",
  "^sexwhore$",
  "^sexx$",
  "^sexxi$",
  "^sexxx$",
  "^sexxxi$",
  "^sexxxy$",
  "^sexxy$",
  "^sexy$",
  "^sexymoma$",
  "^sexyslim$",
  "^sh!t$",
  "^sh1t$",
  "^sh1ter$",
  "^sh1ts$",
  "^sh1tter$",
  "^sh1tz$",
  "^shag$",
  "^shagger$",
  "^shaggin$",
  "^shagging$",
  "^shamedame$",
  "^sharmuta$",
  "^sharmute$",
  "^shat$",
  "^shav$",
  "^shaved$",
  "^shaved beaver$",
  "^shaved pussy$",
  "^shavedbeaver$",
  "^shavedpussy$",
  "^shawtypimp$",
  "^sheeney$",
  "^shemale$",
  "^shhit$",
  "^shibari$",
  "^shinola$",
  "^shipal$",
  "^shirt lifter$",
  "^shit$",
  "^shit ass$",
  "^shit fucker$",
  "^shitass$",
  "^shitbag$",
  "^shitbagger$",
  "^shitblimp$",
  "^shitbrain$",
  "^shitbrains$",
  "^shitbreath$",
  "^shitcan$",
  "^shitcanned$",
  "^shitcunt$",
  "^shitdick$",
  "^shite$",
  "^shiteater$",
  "^shited$",
  "^shitey$",
  "^shitface$",
  "^shitfaced$",
  "^shitfit$",
  "^shitforbrains$",
  "^shitfuck$",
  "^shitfucker$",
  "^shitfull$",
  "^shithapens$",
  "^shithappens$",
  "^shithead$",
  "^shitheads$",
  "^shithole$",
  "^shithouse$",
  "^shiting$",
  "^shitings$",
  "^shitlist$",
  "^shitola$",
  "^shitoutofluck$",
  "^shits$",
  "^shitspitter$",
  "^shitstain$",
  "^shitt$",
  "^shitted$",
  "^shitter$",
  "^shitters$",
  "^shittier$",
  "^shittiest$",
  "^shitting$",
  "^shittings$",
  "^shitty$",
  "^shity$",
  "^shitz$",
  "^shiz$",
  "^shiznit$",
  "^shortfuck$",
  "^shota$",
  "^shrimping$",
  "^shylock$",
  "^shylocks$",
  "^shyt$",
  "^shyte$",
  "^shytty$",
  "^shyty$",
  "^sissy$",
  "^sixsixsix$",
  "^sixtynine$",
  "^sixtyniner$",
  "^skag$",
  "^skanck$",
  "^skank$",
  "^skankbitch$",
  "^skankee$",
  "^skankey$",
  "^skankfuck$",
  "^skanks$",
  "^skankwhore$",
  "^skanky$",
  "^skankybitch$",
  "^skankywhore$",
  "^skeet$",
  "^skinflute$",
  "^skribz$",
  "^skullfuck$",
  "^skum$",
  "^skumbag$",
  "^skurwysyn$",
  "^skwa$",
  "^skwe$",
  "^slag$",
  "^slant$",
  "^slanteye$",
  "^slanty$",
  "^slapper$",
  "^slaughter$",
  "^slave$",
  "^slavedriver$",
  "^sleaze$",
  "^sleazy$",
  "^sleezebag$",
  "^sleezeball$",
  "^slideitin$",
  "^slimeball$",
  "^slimebucket$",
  "^slope$",
  "^slopehead$",
  "^slopeheads$",
  "^sloper$",
  "^slopers$",
  "^slopes$",
  "^slopey$",
  "^slopeys$",
  "^slopies$",
  "^slopy$",
  "^slut$",
  "^slut bucket$",
  "^slutbag$",
  "^slutdumper$",
  "^slutkiss$",
  "^sluts$",
  "^slutt$",
  "^slutting$",
  "^slutty$",
  "^slutwear$",
  "^slutwhore$",
  "^slutz$",
  "^smack$",
  "^smackthemonkey$",
  "^smartass$",
  "^smartasses$",
  "^smeg$",
  "^smegma$",
  "^smoker$",
  "^smut$",
  "^smutty$",
  "^snatch$",
  "^snatchpatch$",
  "^snigger$",
  "^sniggered$",
  "^sniggering$",
  "^sniggers$",
  "^sniper$",
  "^snowback$",
  "^snowballing$",
  "^snownigger$",
  "^snuff$",
  "^sob$",
  "^socksucker$",
  "^sod off$",
  "^sodom$",
  "^sodomise$",
  "^sodomite$",
  "^sodomize$",
  "^sodomy$",
  "^son of a bitch$",
  "^son of a motherless goat$",
  "^son of a whore$",
  "^son-of-a-bitch$",
  "^sonofabitch$",
  "^sonofbitch$",
  "^sooties$",
  "^sooty$",
  "^souse$",
  "^soused$",
  "^spac$",
  "^spade$",
  "^spades$",
  "^spaghettibender$",
  "^spaghettinigger$",
  "^spank$",
  "^spankthemonkey$",
  "^spearchucker$",
  "^spearchuckers$",
  "^sperm$",
  "^spermacide$",
  "^spermbag$",
  "^spermhearder$",
  "^spermherder$",
  "^sphencter$",
  "^spic$",
  "^spick$",
  "^spicks$",
  "^spics$",
  "^spierdalaj$",
  "^spig$",
  "^spigotty$",
  "^spik$",
  "^spiks$",
  "^spitter$",
  "^splittail$",
  "^splooge$",
  "^splooge moose$",
  "^spludge$",
  "^spooge$",
  "^spook$",
  "^spread legs$",
  "^spreadeagle$",
  "^spunk$",
  "^spunky$",
  "^sqeh$",
  "^squa$",
  "^squarehead$",
  "^squareheads$",
  "^squaw$",
  "^squinty$",
  "^squirting$",
  "^stagg$",
  "^steamy$",
  "^stfu$",
  "^stiffy$",
  "^stoned$",
  "^stoner$",
  "^strap on$",
  "^strapon$",
  "^strappado$",
  "^stringer$",
  "^strip$",
  "^strip club$",
  "^stripclub$",
  "^stroke$",
  "^stroking$",
  "^stuinties$",
  "^stupid$",
  "^stupidfuck$",
  "^stupidfucker$",
  "^style doggy$",
  "^suck$",
  "^suckass$",
  "^suckdick$",
  "^sucked$",
  "^sucker$",
  "^sucking$",
  "^suckme$",
  "^suckmyass$",
  "^suckmydick$",
  "^suckmytit$",
  "^suckoff$",
  "^sucks$",
  "^suicide$",
  "^suicide girl$",
  "^suicide girls$",
  "^suicidegirl$",
  "^suicidegirls$",
  "^suka$",
  "^sultry$",
  "^sultry women$",
  "^sultrywoman$",
  "^sultrywomen$",
  "^sumofabiatch$",
  "^swallow$",
  "^swallower$",
  "^swalow$",
  "^swamp guinea$",
  "^swamp guineas$",
  "^swastika$",
  "^swinger$",
  "^syphilis$",
  "^t i t$",
  "^t i ts$",
  "^t1t$",
  "^t1tt1e5$",
  "^t1tties$",
  "^taboo$",
  "^tacohead$",
  "^tacoheads$",
  "^taff$",
  "^taig$",
  "^tainted$",
  "^tainted love$",
  "^take off your$",
  "^taking the piss$",
  "^tampon$",
  "^tantra$",
  "^tar babies$",
  "^tar baby$",
  "^tarbaby$",
  "^tard$",
  "^tart$",
  "^taste my$",
  "^tastemy$",
  "^tawdry$",
  "^tea bagging$",
  "^teabagging$",
  "^teat$",
  "^teets$",
  "^teez$",
  "^terd$",
  "^terror$",
  "^terrorist$",
  "^teste$",
  "^testee$",
  "^testes$",
  "^testical$",
  "^testicle$",
  "^testicles$",
  "^testis$",
  "^thicklip$",
  "^thicklips$",
  "^thirdeye$",
  "^thirdleg$",
  "^threesome$",
  "^threeway$",
  "^throat$",
  "^throating$",
  "^thrust$",
  "^thug$",
  "^thundercunt$",
  "^ti$",
  "^tied up$",
  "^tight white$",
  "^timber nigger$",
  "^timber niggers$",
  "^timbernigger$",
  "^tinkle$",
  "^tit$",
  "^tit wank$",
  "^titbitnipply$",
  "^titfuck$",
  "^titfucker$",
  "^titfuckin$",
  "^titi$",
  "^tities$",
  "^titjob$",
  "^titlicker$",
  "^titlover$",
  "^tits$",
  "^titt$",
  "^tittie$",
  "^tittie5$",
  "^tittiefucker$",
  "^titties$",
  "^tittis$",
  "^titty$",
  "^tittyfuck$",
  "^tittyfucker$",
  "^tittys$",
  "^tittywank$",
  "^titwank$",
  "^tity$",
  "^to murder$",
  "^toke$",
  "^tongethruster$",
  "^tongue in a$",
  "^tongueina$",
  "^tonguethrust$",
  "^tonguetramp$",
  "^toots$",
  "^topless$",
  "^tortur$",
  "^torture$",
  "^tosser$",
  "^towel head$",
  "^towel heads$",
  "^towelhead$",
  "^trailertrash$",
  "^tramp$",
  "^trannie$",
  "^tranny$",
  "^transsexual$",
  "^transvestite$",
  "^trashy$",
  "^tribadism$",
  "^triplex$",
  "^trisexual$",
  "^trois$",
  "^trojan$",
  "^trombone$",
  "^trots$",
  "^trumped$",
  "^tub girl$",
  "^tubgirl$",
  "^tuckahoe$",
  "^tunneloflove$",
  "^turd$",
  "^turnon$",
  "^tush$",
  "^tushy$",
  "^tw4t$",
  "^twat$",
  "^twathead$",
  "^twatlips$",
  "^twats$",
  "^twatty$",
  "^twatwaffle$",
  "^twink$",
  "^twinkie$",
  "^two fingers$",
  "^two fingers with tongue$",
  "^two girls one cup$",
  "^twobitwhore$",
  "^twunt$",
  "^twunter$",
  "^udge packer$",
  "^ukrop$",
  "^uncle tom$",
  "^unclefucker$",
  "^undies$",
  "^undressing$",
  "^unfuckable$",
  "^unwed$",
  "^upskirt$",
  "^uptheass$",
  "^upthebutt$",
  "^urethra$",
  "^urethra play$",
  "^urethraplay$",
  "^urinal$",
  "^urinary$",
  "^urinate$",
  "^urine$",
  "^urophilia$",
  "^usama$",
  "^ussys$",
  "^uterus$",
  "^uzi$",
  "^v a g i n a$",
  "^v14gra$",
  "^v1gra$",
  "^v4gra$",
  "^va-j-j$",
  "^va1jina$",
  "^vag$",
  "^vag1na$",
  "^vagina$|^vaginae$|^vaginal$|^vagiina$",
  "^vaj1na$",
  "^vajayjay$",
  "^vajina$",
  "^valium$",
  "^venus mound$",
  "^veqtable$",
  "^vgra$",
  "^viagra$",
  "^vibe$",
  "^vibr$",
  "^vibrater$",
  "^vibrator$",
  "^vietcong$",
  "^violet wand$",
  "^virgin$",
  "^virginbreaker$",
  "^vittu$",
  "^vixen$",
  "^vjayjay$",
  "^vodka$",
  "^vomit$",
  "^vorarephilia$",
  "^voyeur$",
  "^vulgar$",
  "^vullva$",
  "^vulva$",
  "^w00se$",
  "^w0p$",
  "^wab$",
  "^wad$",
  "^wang$",
  "^wank$",
  "^wanker$",
  "^wanking$",
  "^wankjob$",
  "^wanky$",
  "^waysted$",
  "^wazoo$",
  "^wedgie$",
  "^weed$",
  "^weenie$",
  "^weewee$",
  "^weiner$",
  "^weirdo$",
  "^welcher$",
  "^wench$",
  "^wet dream$",
  "^wetb$",
  "^wetback$",
  "^wetbacks$",
  "^wetdream$",
  "^wetspot$",
  "^wh00r$",
  "^wh0re$",
  "^wh0reface$",
  "^whacker$",
  "^whash$",
  "^whigger$",
  "^whiggers$",
  "^whiskeydick$",
  "^whiskydick$",
  "^whit$",
  "^white power$",
  "^white trash$",
  "^whitenigger$",
  "^whitepower$",
  "^whites$",
  "^whitetrash$",
  "^whitey$",
  "^whiteys$",
  "^whities$",
  "^whiz$",
  "^whoar$",
  "^whop$",
  "^whoralicious$",
  "^whore$",
  "^whorealicious$",
  "^whorebag$",
  "^whored$",
  "^whoreface$",
  "^whorefucker$",
  "^whorehopper$",
  "^whorehouse$",
  "^whores$",
  "^whoring$",
  "^wichser$",
  "^wigga$",
  "^wiggas$",
  "^wigger$",
  "^wiggers$",
  "^willie$",
  "^willies$",
  "^williewanker$",
  "^willy$",
  "^window licker$",
  "^wiseass$",
  "^wiseasses$",
  "^wn$",
  "^wog$",
  "^wogs$",
  "^woman chest$",
  "^womans chest$",
  "^womb$",
  "^woody$",
  "^wop$",
  "^wrapping men$",
  "^wrinkled starfish$",
  "^wtf$",
  "^wuss$",
  "^wuzzie$",
  "^x-rated$",
  "^xkwe$",
  "^xrated$",
  "^xtc$",
  "^xx$",
  "^xxx$",
  "^xxxxxx$",
  "^yank$",
  "^yaoi$",
  "^yarpie$",
  "^yarpies$",
  "^yeasty$",
  "^yed$",
  "^yellow showers$",
  "^yellowman$",
  "^yellowshowers$",
  "^yid$",
  "^yids$",
  "^yiffy$",
  "^yobbo$",
  "^yourboobs$",
  "^yourpenis$",
  "^yourtits$",
  "^zabourah$",
  "^zibbi$",
  "^zigabo$",
  "^zigabos$",
  "^zipperhead$",
  "^zipperheads$",
  "^zoophile$",
  "^zoophilia$",
  "^zubb$"
];

export default en;