/**
 * Set an array of finnish abusive words
 */
const fi: string[] = [
  "^alfred nussi$",
  "^bylsiä$",
  "^haahka$",
  "^haista paska$",
  "^haista vittu$",
  "^hatullinen$",
  "^helvetisti$",
  "^hevonkuusi$",
  "^hevonpaska$",
  "^hevonperse$",
  "^hevonvittu$",
  "^hevonvitunperse$",
  "^hitosti$",
  "^hitto$",
  "^huorata$",
  "^hässiä$",
  "^juosten kustu$",
  "^jutku$",
  "^jutsku$",
  "^jätkä$",
  "^kananpaska$",
  "^koiranpaska$",
  "^kuin esterin perseestä$",
  "^kulli$",
  "^kullinluikaus$",
  "^kuppainen$",
  "^kusaista$",
  "^kuseksia$",
  "^kusettaa$",
  "^kusi",
  "^kusipää$",
  "^kusta$",
  "^kyrp[a-zäöåš]+",
  "^kyrvitys$",
  "^lahtari$",
  "^lutka$",
  "^molo$",
  "^molopää$",
  "^mulkero$",
  "^mulkku$",
  "^mulkvisti$",
  "^muna$",
  "^munapää$",
  "^munaton$",
  "^mutakuono$",
  "^mutiainen$",
  "^naida$",
  "^nainti$",
  "^narttu$",
  "^neekeri$",
  "^nekru$",
  "^nuolla persettä$",
  "^nussi[a-zäöåš]+",
  "^paljaalla$",
  "^palli$",
  "^pallit$",
  "^paneskella$",
  "^panettaa$",
  "^panna$",
  "^pano$",
  "^pantava$",
  "^paska",
  "^paskiainen$",
  "^paskoa$",
  "^pehko$",
  "^pentele$",
  "^perkele$",
  "^perkeleesti$",
  "^persaukinen$",
  "^perse$",
  "^perseennuolija$",
  "^perseet olalla$",
  "^persereikä$",
  "^perseääliö$",
  "^persläpi$",
  "^perspano$",
  "^persvako$",
  "^pilkunnussija$",
  "^pillu$",
  "^pillut$",
  "^pipari$",
  "^piru$",
  "^pistää$",
  "^pyllyvako$",
  "^reikä$",
  "^reva$",
  "^ripsipiirakka$",
  "^runkata$",
  "^runkk[a-zäöåš]+",
  "^ryssä$",
  "^rättipää$",
  "^saatanasti$",
  "^suklaaosasto$",
  "^tavara$",
  "^toosa$",
  "^tuhkaluukku$",
  "^tumputtaa$",
  "^turpasauna$",
  "^tussu$",
  "^tussukka$",
  "^tussut$",
  "^vakipano$",
  "^vetää käteen$",
  "^viiksi$",
  "^vittu",
  "^vitu[a-zäöåš]+",
  "^äpärä$",
];

export default fi;